# Generated by Django 5.2.1 on 2026-03-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('rua', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=20)),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('cep', models.CharField(max_length=8)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('estoque', models.IntegerField()),
                ('dt_adicao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
