# Generated by Django 5.2.1 on 2026-03-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0002_remove_produto_estoque_produto_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dt_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dt_adicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
