# Generated by Django 5.2.1 on 2026-03-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0005_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
