# Generated by Django 5.2.1 on 2026-03-11 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0008_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
    ]
