# Generated by Django 5.2.1 on 2026-03-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0009_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
