# Generated by Django 5.2.1 on 2026-03-28 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0010_alter_produto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cep',
        ),
    ]
