# Generated by Django 5.2.1 on 2026-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0011_remove_client_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
