# Generated by Django 5.2.1 on 2026-09-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0015_venda_status_anotado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bairro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero',
            field=models.PositiveIntegerField(blank=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rua',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('anotado', 'Anotado')], max_length=20),
        ),
    ]
