# Generated by Django 5.2.1 on 2026-09-16 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0016_alter_client_bairro_alter_client_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PagamentoParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_pagamento', models.CharField(max_length=20)),
                ('dt_pagamento', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_parciais', to='front_end.venda')),
            ],
        ),
    ]
