# Generated by Django 5.2.1 on 2026-09-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0017_venda_valor_pago_pagamentoparcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoparcial',
            name='parcelas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venda',
            name='parcelas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
