# Generated by Django 5.2.1 on 2026-09-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0018_venda_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
